#include "TH1.h"
#include "TTree.h"
#include "TKey.h"
#include "Riostream.h"
#include <TCanvas.h>
#include <TLatex.h>
#include "TGraphErrors.h"
#include "TLegend.h"
#include <TPad.h>
#include <sstream>
#include "TVectorD.h"
#include "TChain.h"
#include "TGraph.h"
#include "TFile.h"

using std::string;
using std::cout;
using std::endl;
using std::istringstream;

double LUMI = 35.9;
double BR = (0.33*0.33*0.67*3 + 0.33*0.33*0.33);

int makeLimitTemplates_aQGC(std::string infile, std::string outfile)
{
  std::string inputfilename=(infile+".root").c_str();
  TChain *tree=new TChain("ST_Tree");
  tree->Add(inputfilename.c_str());
  std::cout<<"Opened input file "<<inputfilename<<std::endl;

  Double_t        ST_rwgt67_MuMu;
  Double_t        ST_rwgt68_MuMu;
  Double_t        ST_rwgt69_MuMu;
  Double_t        ST_rwgt70_MuMu;
  Double_t        ST_rwgt71_MuMu;
  Double_t        ST_rwgt72_MuMu;
  Double_t        ST_rwgt73_MuMu;
  Double_t        ST_rwgt74_MuMu;
  Double_t        ST_rwgt75_MuMu;
  Double_t        ST_rwgt76_MuMu;
  Double_t        ST_rwgt77_MuMu;
  Double_t        ST_bkg_MuMu;
  Double_t        ST_rwgt67_ElMu;
  Double_t        ST_rwgt68_ElMu;
  Double_t        ST_rwgt69_ElMu;
  Double_t        ST_rwgt70_ElMu;
  Double_t        ST_rwgt71_ElMu;
  Double_t        ST_rwgt72_ElMu;
  Double_t        ST_rwgt73_ElMu;
  Double_t        ST_rwgt74_ElMu;
  Double_t        ST_rwgt75_ElMu;
  Double_t        ST_rwgt76_ElMu;
  Double_t        ST_rwgt77_ElMu;
  Double_t        ST_bkg_ElMu;
  Double_t        ST_rwgt67_ElEl;
  Double_t        ST_rwgt68_ElEl;
  Double_t        ST_rwgt69_ElEl;
  Double_t        ST_rwgt70_ElEl;
  Double_t        ST_rwgt71_ElEl;
  Double_t        ST_rwgt72_ElEl;
  Double_t        ST_rwgt73_ElEl;
  Double_t        ST_rwgt74_ElEl;
  Double_t        ST_rwgt75_ElEl;
  Double_t        ST_rwgt76_ElEl;
  Double_t        ST_rwgt77_ElEl;
  Double_t        ST_bkg_ElEl;
  Double_t        weight_rwgt67_MuMu;
  Double_t        weight_rwgt68_MuMu;
  Double_t        weight_rwgt69_MuMu;
  Double_t        weight_rwgt70_MuMu;
  Double_t        weight_rwgt71_MuMu;
  Double_t        weight_rwgt72_MuMu;
  Double_t        weight_rwgt73_MuMu;
  Double_t        weight_rwgt74_MuMu;
  Double_t        weight_rwgt75_MuMu;
  Double_t        weight_rwgt76_MuMu;
  Double_t        weight_rwgt77_MuMu;
  Double_t        weight_bkg_MuMu;
  Double_t        weight_rwgt67_ElMu;
  Double_t        weight_rwgt68_ElMu;
  Double_t        weight_rwgt69_ElMu;
  Double_t        weight_rwgt70_ElMu;
  Double_t        weight_rwgt71_ElMu;
  Double_t        weight_rwgt72_ElMu;
  Double_t        weight_rwgt73_ElMu;
  Double_t        weight_rwgt74_ElMu;
  Double_t        weight_rwgt75_ElMu;
  Double_t        weight_rwgt76_ElMu;
  Double_t        weight_rwgt77_ElMu;
  Double_t        weight_bkg_ElMu;
  Double_t        weight_rwgt67_ElEl;
  Double_t        weight_rwgt68_ElEl;
  Double_t        weight_rwgt69_ElEl;
  Double_t        weight_rwgt70_ElEl;
  Double_t        weight_rwgt71_ElEl;
  Double_t        weight_rwgt72_ElEl;
  Double_t        weight_rwgt73_ElEl;
  Double_t        weight_rwgt74_ElEl;
  Double_t        weight_rwgt75_ElEl;
  Double_t        weight_rwgt76_ElEl;
  Double_t        weight_rwgt77_ElEl;
  Double_t        weight_bkg_ElEl;

  tree->SetBranchAddress("ST_rwgt67_MuMu", &(ST_rwgt67_MuMu));
  tree->SetBranchAddress("ST_rwgt68_MuMu", &(ST_rwgt68_MuMu));  
  tree->SetBranchAddress("ST_rwgt69_MuMu", &(ST_rwgt69_MuMu));
  tree->SetBranchAddress("ST_rwgt70_MuMu", &(ST_rwgt70_MuMu));
  tree->SetBranchAddress("ST_rwgt71_MuMu", &(ST_rwgt71_MuMu));
  tree->SetBranchAddress("ST_rwgt72_MuMu", &(ST_rwgt72_MuMu));
  tree->SetBranchAddress("ST_rwgt73_MuMu", &(ST_rwgt73_MuMu));
  tree->SetBranchAddress("ST_rwgt74_MuMu", &(ST_rwgt74_MuMu));
  tree->SetBranchAddress("ST_rwgt75_MuMu", &(ST_rwgt75_MuMu));
  tree->SetBranchAddress("ST_rwgt76_MuMu", &(ST_rwgt76_MuMu));
  tree->SetBranchAddress("ST_rwgt77_MuMu", &(ST_rwgt77_MuMu));
  tree->SetBranchAddress("ST_bkg_MuMu", &(ST_bkg_MuMu));
  tree->SetBranchAddress("ST_rwgt67_ElMu", &(ST_rwgt67_ElMu));
  tree->SetBranchAddress("ST_rwgt68_ElMu", &(ST_rwgt68_ElMu));
  tree->SetBranchAddress("ST_rwgt69_ElMu", &(ST_rwgt69_ElMu));
  tree->SetBranchAddress("ST_rwgt70_ElMu", &(ST_rwgt70_ElMu));
  tree->SetBranchAddress("ST_rwgt71_ElMu", &(ST_rwgt71_ElMu));
  tree->SetBranchAddress("ST_rwgt72_ElMu", &(ST_rwgt72_ElMu));
  tree->SetBranchAddress("ST_rwgt73_ElMu", &(ST_rwgt73_ElMu));
  tree->SetBranchAddress("ST_rwgt74_ElMu", &(ST_rwgt74_ElMu));
  tree->SetBranchAddress("ST_rwgt75_ElMu", &(ST_rwgt75_ElMu));
  tree->SetBranchAddress("ST_rwgt76_ElMu", &(ST_rwgt76_ElMu));
  tree->SetBranchAddress("ST_rwgt77_ElMu", &(ST_rwgt77_ElMu));
  tree->SetBranchAddress("ST_bkg_ElMu", &(ST_bkg_ElMu));
  tree->SetBranchAddress("ST_rwgt67_ElEl", &(ST_rwgt67_ElEl));
  tree->SetBranchAddress("ST_rwgt68_ElEl", &(ST_rwgt68_ElEl));
  tree->SetBranchAddress("ST_rwgt69_ElEl", &(ST_rwgt69_ElEl));
  tree->SetBranchAddress("ST_rwgt70_ElEl", &(ST_rwgt70_ElEl));
  tree->SetBranchAddress("ST_rwgt71_ElEl", &(ST_rwgt71_ElEl));
  tree->SetBranchAddress("ST_rwgt72_ElEl", &(ST_rwgt72_ElEl));
  tree->SetBranchAddress("ST_rwgt73_ElEl", &(ST_rwgt73_ElEl));
  tree->SetBranchAddress("ST_rwgt74_ElEl", &(ST_rwgt74_ElEl));
  tree->SetBranchAddress("ST_rwgt75_ElEl", &(ST_rwgt75_ElEl));
  tree->SetBranchAddress("ST_rwgt76_ElEl", &(ST_rwgt76_ElEl));
  tree->SetBranchAddress("ST_rwgt77_ElEl", &(ST_rwgt77_ElEl));
  tree->SetBranchAddress("ST_bkg_ElEl", &(ST_bkg_ElEl));
  tree->SetBranchAddress("weight_rwgt67_MuMu", &(weight_rwgt67_MuMu));
  tree->SetBranchAddress("weight_rwgt68_MuMu", &(weight_rwgt68_MuMu));
  tree->SetBranchAddress("weight_rwgt69_MuMu", &(weight_rwgt69_MuMu));
  tree->SetBranchAddress("weight_rwgt70_MuMu", &(weight_rwgt70_MuMu));
  tree->SetBranchAddress("weight_rwgt71_MuMu", &(weight_rwgt71_MuMu));
  tree->SetBranchAddress("weight_rwgt72_MuMu", &(weight_rwgt72_MuMu));
  tree->SetBranchAddress("weight_rwgt73_MuMu", &(weight_rwgt73_MuMu));
  tree->SetBranchAddress("weight_rwgt74_MuMu", &(weight_rwgt74_MuMu));
  tree->SetBranchAddress("weight_rwgt75_MuMu", &(weight_rwgt75_MuMu));
  tree->SetBranchAddress("weight_rwgt76_MuMu", &(weight_rwgt76_MuMu));
  tree->SetBranchAddress("weight_rwgt77_MuMu", &(weight_rwgt77_MuMu));
  tree->SetBranchAddress("weight_bkg_MuMu", &(weight_bkg_MuMu));
  tree->SetBranchAddress("weight_rwgt67_ElMu", &(weight_rwgt67_ElMu));
  tree->SetBranchAddress("weight_rwgt68_ElMu", &(weight_rwgt68_ElMu));
  tree->SetBranchAddress("weight_rwgt69_ElMu", &(weight_rwgt69_ElMu));
  tree->SetBranchAddress("weight_rwgt70_ElMu", &(weight_rwgt70_ElMu));
  tree->SetBranchAddress("weight_rwgt71_ElMu", &(weight_rwgt71_ElMu));
  tree->SetBranchAddress("weight_rwgt72_ElMu", &(weight_rwgt72_ElMu));
  tree->SetBranchAddress("weight_rwgt73_ElMu", &(weight_rwgt73_ElMu));
  tree->SetBranchAddress("weight_rwgt74_ElMu", &(weight_rwgt74_ElMu));
  tree->SetBranchAddress("weight_rwgt75_ElMu", &(weight_rwgt75_ElMu));
  tree->SetBranchAddress("weight_rwgt76_ElMu", &(weight_rwgt76_ElMu));
  tree->SetBranchAddress("weight_rwgt77_ElMu", &(weight_rwgt77_ElMu));
  tree->SetBranchAddress("weight_bkg_ElMu", &(weight_bkg_ElMu));
  tree->SetBranchAddress("weight_rwgt67_ElEl", &(weight_rwgt67_ElEl));
  tree->SetBranchAddress("weight_rwgt68_ElEl", &(weight_rwgt68_ElEl));
  tree->SetBranchAddress("weight_rwgt69_ElEl", &(weight_rwgt69_ElEl));
  tree->SetBranchAddress("weight_rwgt70_ElEl", &(weight_rwgt70_ElEl));
  tree->SetBranchAddress("weight_rwgt71_ElEl", &(weight_rwgt71_ElEl));
  tree->SetBranchAddress("weight_rwgt72_ElEl", &(weight_rwgt72_ElEl));
  tree->SetBranchAddress("weight_rwgt73_ElEl", &(weight_rwgt73_ElEl));
  tree->SetBranchAddress("weight_rwgt74_ElEl", &(weight_rwgt74_ElEl));
  tree->SetBranchAddress("weight_rwgt75_ElEl", &(weight_rwgt75_ElEl));
  tree->SetBranchAddress("weight_rwgt76_ElEl", &(weight_rwgt76_ElEl));
  tree->SetBranchAddress("weight_rwgt77_ElEl", &(weight_rwgt77_ElEl));
  tree->SetBranchAddress("weight_bkg_ElEl", &(weight_bkg_ElEl));

  Float_t rebin_array[] = {0, 250.0, 500.0, 750.0, 1000.0, 1250.0, 1500.0, 1750.0, 2000.0, 2500.0, 3000.0, 4000.0, 5000.0, 10000.0};
  Int_t  bin = sizeof(rebin_array)/sizeof(Float_t) - 1;
  TH1F *h_ST_rebin = new TH1F("h_ST_rebin", "h_ST_rebin", bin, rebin_array);  
  TH1F *h_ST_rebin_2 = new TH1F("h_ST_rebin_2", "h_ST_rebin_2", bin, rebin_array);

  TH1F *h_ST_rgwt67_MuMu = new TH1F("h_ST_rgwt67_MuMu", "h_ST_rgwt67_MuMu", 20.0, 0.0, 10000.0); h_ST_rgwt67_MuMu->Sumw2();
  TH1F *h_ST_rgwt68_MuMu = new TH1F("h_ST_rgwt68_MuMu", "h_ST_rgwt68_MuMu", 20.0, 0.0, 10000.0); h_ST_rgwt68_MuMu->Sumw2();
  TH1F *h_ST_rgwt69_MuMu = new TH1F("h_ST_rgwt69_MuMu", "h_ST_rgwt69_MuMu", 20.0, 0.0, 10000.0); h_ST_rgwt69_MuMu->Sumw2();
  TH1F *h_ST_rgwt70_MuMu = new TH1F("h_ST_rgwt70_MuMu", "h_ST_rgwt70_MuMu", 20.0, 0.0, 10000.0); h_ST_rgwt70_MuMu->Sumw2();
  TH1F *h_ST_rgwt71_MuMu = new TH1F("h_ST_rgwt71_MuMu", "h_ST_rgwt71_MuMu", 20.0, 0.0, 10000.0); h_ST_rgwt71_MuMu->Sumw2();
  TH1F *h_ST_rgwt72_MuMu = new TH1F("h_ST_rgwt72_MuMu", "h_ST_rgwt72_MuMu", 20.0, 0.0, 10000.0); h_ST_rgwt72_MuMu->Sumw2();
  TH1F *h_ST_rgwt73_MuMu = new TH1F("h_ST_rgwt73_MuMu", "h_ST_rgwt73_MuMu", 20.0, 0.0, 10000.0); h_ST_rgwt73_MuMu->Sumw2();
  TH1F *h_ST_rgwt74_MuMu = new TH1F("h_ST_rgwt74_MuMu", "h_ST_rgwt74_MuMu", 20.0, 0.0, 10000.0); h_ST_rgwt74_MuMu->Sumw2();
  TH1F *h_ST_rgwt75_MuMu = new TH1F("h_ST_rgwt75_MuMu", "h_ST_rgwt75_MuMu", 20.0, 0.0, 10000.0); h_ST_rgwt75_MuMu->Sumw2();
  TH1F *h_ST_rgwt76_MuMu = new TH1F("h_ST_rgwt76_MuMu", "h_ST_rgwt76_MuMu", 20.0, 0.0, 10000.0); h_ST_rgwt76_MuMu->Sumw2();
  TH1F *h_ST_rgwt77_MuMu = new TH1F("h_ST_rgwt77_MuMu", "h_ST_rgwt77_MuMu", 20.0, 0.0, 10000.0); h_ST_rgwt77_MuMu->Sumw2();  
  TH1F *h_ST_bkg_MuMu = new TH1F("h_ST_bkg_MuMu", "h_ST_bkg_MuMu", 20.0, 0.0, 10000.0); h_ST_bkg_MuMu->Sumw2();
  TH1F *h_ST_rgwt67_ElMu = new TH1F("h_ST_rgwt67_ElMu", "h_ST_rgwt67_ElMu", 20.0, 0.0, 10000.0); h_ST_rgwt67_ElMu->Sumw2();
  TH1F *h_ST_rgwt68_ElMu = new TH1F("h_ST_rgwt68_ElMu", "h_ST_rgwt68_ElMu", 20.0, 0.0, 10000.0); h_ST_rgwt68_ElMu->Sumw2();
  TH1F *h_ST_rgwt69_ElMu = new TH1F("h_ST_rgwt69_ElMu", "h_ST_rgwt69_ElMu", 20.0, 0.0, 10000.0); h_ST_rgwt69_ElMu->Sumw2();
  TH1F *h_ST_rgwt70_ElMu = new TH1F("h_ST_rgwt70_ElMu", "h_ST_rgwt70_ElMu", 20.0, 0.0, 10000.0); h_ST_rgwt70_ElMu->Sumw2();
  TH1F *h_ST_rgwt71_ElMu = new TH1F("h_ST_rgwt71_ElMu", "h_ST_rgwt71_ElMu", 20.0, 0.0, 10000.0); h_ST_rgwt71_ElMu->Sumw2();
  TH1F *h_ST_rgwt72_ElMu = new TH1F("h_ST_rgwt72_ElMu", "h_ST_rgwt72_ElMu", 20.0, 0.0, 10000.0); h_ST_rgwt72_ElMu->Sumw2();
  TH1F *h_ST_rgwt73_ElMu = new TH1F("h_ST_rgwt73_ElMu", "h_ST_rgwt73_ElMu", 20.0, 0.0, 10000.0); h_ST_rgwt73_ElMu->Sumw2();
  TH1F *h_ST_rgwt74_ElMu = new TH1F("h_ST_rgwt74_ElMu", "h_ST_rgwt74_ElMu", 20.0, 0.0, 10000.0); h_ST_rgwt74_ElMu->Sumw2();
  TH1F *h_ST_rgwt75_ElMu = new TH1F("h_ST_rgwt75_ElMu", "h_ST_rgwt75_ElMu", 20.0, 0.0, 10000.0); h_ST_rgwt75_ElMu->Sumw2();
  TH1F *h_ST_rgwt76_ElMu = new TH1F("h_ST_rgwt76_ElMu", "h_ST_rgwt76_ElMu", 20.0, 0.0, 10000.0); h_ST_rgwt76_ElMu->Sumw2();
  TH1F *h_ST_rgwt77_ElMu = new TH1F("h_ST_rgwt77_ElMu", "h_ST_rgwt77_ElMu", 20.0, 0.0, 10000.0); h_ST_rgwt77_ElMu->Sumw2();
  TH1F *h_ST_bkg_ElMu = new TH1F("h_ST_bkg_ElMu", "h_ST_bkg_ElMu", 20.0, 0.0, 10000.0); h_ST_bkg_ElMu->Sumw2(); 
  TH1F *h_ST_rgwt67_ElEl = new TH1F("h_ST_rgwt67_ElEl", "h_ST_rgwt67_ElEl", 20.0, 0.0, 10000.0); h_ST_rgwt67_ElEl->Sumw2();
  TH1F *h_ST_rgwt68_ElEl = new TH1F("h_ST_rgwt68_ElEl", "h_ST_rgwt68_ElEl", 20.0, 0.0, 10000.0); h_ST_rgwt68_ElEl->Sumw2();
  TH1F *h_ST_rgwt69_ElEl = new TH1F("h_ST_rgwt69_ElEl", "h_ST_rgwt69_ElEl", 20.0, 0.0, 10000.0); h_ST_rgwt69_ElEl->Sumw2();
  TH1F *h_ST_rgwt70_ElEl = new TH1F("h_ST_rgwt70_ElEl", "h_ST_rgwt70_ElEl", 20.0, 0.0, 10000.0); h_ST_rgwt70_ElEl->Sumw2();
  TH1F *h_ST_rgwt71_ElEl = new TH1F("h_ST_rgwt71_ElEl", "h_ST_rgwt71_ElEl", 20.0, 0.0, 10000.0); h_ST_rgwt71_ElEl->Sumw2();
  TH1F *h_ST_rgwt72_ElEl = new TH1F("h_ST_rgwt72_ElEl", "h_ST_rgwt72_ElEl", 20.0, 0.0, 10000.0); h_ST_rgwt72_ElEl->Sumw2();
  TH1F *h_ST_rgwt73_ElEl = new TH1F("h_ST_rgwt73_ElEl", "h_ST_rgwt73_ElEl", 20.0, 0.0, 10000.0); h_ST_rgwt73_ElEl->Sumw2();
  TH1F *h_ST_rgwt74_ElEl = new TH1F("h_ST_rgwt74_ElEl", "h_ST_rgwt74_ElEl", 20.0, 0.0, 10000.0); h_ST_rgwt74_ElEl->Sumw2();
  TH1F *h_ST_rgwt75_ElEl = new TH1F("h_ST_rgwt75_ElEl", "h_ST_rgwt75_ElEl", 20.0, 0.0, 10000.0); h_ST_rgwt75_ElEl->Sumw2();
  TH1F *h_ST_rgwt76_ElEl = new TH1F("h_ST_rgwt76_ElEl", "h_ST_rgwt76_ElEl", 20.0, 0.0, 10000.0); h_ST_rgwt76_ElEl->Sumw2();
  TH1F *h_ST_rgwt77_ElEl = new TH1F("h_ST_rgwt77_ElEl", "h_ST_rgwt77_ElEl", 20.0, 0.0, 10000.0); h_ST_rgwt77_ElEl->Sumw2();
  TH1F *h_ST_bkg_ElEl = new TH1F("h_ST_bkg_ElEl", "h_ST_bkg_ElEl", 20.0, 0.0, 10000.0); h_ST_bkg_ElEl->Sumw2();
  TH1F *h_ST_rgwt67_MuMu_MinusSM = new TH1F("h_ST_rgwt67_MuMu_MinusSM", "h_ST_rgwt67_MuMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt67_MuMu_MinusSM->Sumw2(); 
  TH1F *h_ST_rgwt68_MuMu_MinusSM = new TH1F("h_ST_rgwt68_MuMu_MinusSM", "h_ST_rgwt68_MuMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt68_MuMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt69_MuMu_MinusSM = new TH1F("h_ST_rgwt69_MuMu_MinusSM", "h_ST_rgwt69_MuMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt69_MuMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt70_MuMu_MinusSM = new TH1F("h_ST_rgwt70_MuMu_MinusSM", "h_ST_rgwt70_MuMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt70_MuMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt71_MuMu_MinusSM = new TH1F("h_ST_rgwt71_MuMu_MinusSM", "h_ST_rgwt71_MuMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt71_MuMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt72_MuMu_MinusSM = new TH1F("h_ST_rgwt72_MuMu_MinusSM", "h_ST_rgwt72_MuMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt72_MuMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt73_MuMu_MinusSM = new TH1F("h_ST_rgwt73_MuMu_MinusSM", "h_ST_rgwt73_MuMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt73_MuMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt74_MuMu_MinusSM = new TH1F("h_ST_rgwt74_MuMu_MinusSM", "h_ST_rgwt74_MuMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt74_MuMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt75_MuMu_MinusSM = new TH1F("h_ST_rgwt75_MuMu_MinusSM", "h_ST_rgwt75_MuMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt75_MuMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt76_MuMu_MinusSM = new TH1F("h_ST_rgwt76_MuMu_MinusSM", "h_ST_rgwt76_MuMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt76_MuMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt77_MuMu_MinusSM = new TH1F("h_ST_rgwt77_MuMu_MinusSM", "h_ST_rgwt77_MuMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt77_MuMu_MinusSM->Sumw2();
  TH1F *h_ST_bkg_MuMu_PlusSM = new TH1F("h_ST_bkg_MuMu_PlusSM", "h_ST_bkg_MuMu_PlusSM", 20.0, 0.0, 10000.0); h_ST_bkg_MuMu_PlusSM->Sumw2();
  TH1F *h_ST_rgwt67_ElMu_MinusSM = new TH1F("h_ST_rgwt67_ElMu_MinusSM", "h_ST_rgwt67_ElMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt67_ElMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt68_ElMu_MinusSM = new TH1F("h_ST_rgwt68_ElMu_MinusSM", "h_ST_rgwt68_ElMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt68_ElMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt69_ElMu_MinusSM = new TH1F("h_ST_rgwt69_ElMu_MinusSM", "h_ST_rgwt69_ElMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt69_ElMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt70_ElMu_MinusSM = new TH1F("h_ST_rgwt70_ElMu_MinusSM", "h_ST_rgwt70_ElMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt70_ElMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt71_ElMu_MinusSM = new TH1F("h_ST_rgwt71_ElMu_MinusSM", "h_ST_rgwt71_ElMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt71_ElMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt72_ElMu_MinusSM = new TH1F("h_ST_rgwt72_ElMu_MinusSM", "h_ST_rgwt72_ElMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt72_ElMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt73_ElMu_MinusSM = new TH1F("h_ST_rgwt73_ElMu_MinusSM", "h_ST_rgwt73_ElMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt73_ElMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt74_ElMu_MinusSM = new TH1F("h_ST_rgwt74_ElMu_MinusSM", "h_ST_rgwt74_ElMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt74_ElMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt75_ElMu_MinusSM = new TH1F("h_ST_rgwt75_ElMu_MinusSM", "h_ST_rgwt75_ElMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt75_ElMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt76_ElMu_MinusSM = new TH1F("h_ST_rgwt76_ElMu_MinusSM", "h_ST_rgwt76_ElMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt76_ElMu_MinusSM->Sumw2();
  TH1F *h_ST_rgwt77_ElMu_MinusSM = new TH1F("h_ST_rgwt77_ElMu_MinusSM", "h_ST_rgwt77_ElMu_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt77_ElMu_MinusSM->Sumw2();
  TH1F *h_ST_bkg_ElMu_PlusSM = new TH1F("h_ST_bkg_ElMu_PlusSM", "h_ST_bkg_ElMu_PlusSM", 20.0, 0.0, 10000.0); h_ST_bkg_ElMu_PlusSM->Sumw2();
  TH1F *h_ST_rgwt67_ElEl_MinusSM = new TH1F("h_ST_rgwt67_ElEl_MinusSM", "h_ST_rgwt67_ElEl_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt67_ElEl_MinusSM->Sumw2();
  TH1F *h_ST_rgwt68_ElEl_MinusSM = new TH1F("h_ST_rgwt68_ElEl_MinusSM", "h_ST_rgwt68_ElEl_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt68_ElEl_MinusSM->Sumw2();
  TH1F *h_ST_rgwt69_ElEl_MinusSM = new TH1F("h_ST_rgwt69_ElEl_MinusSM", "h_ST_rgwt69_ElEl_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt69_ElEl_MinusSM->Sumw2();
  TH1F *h_ST_rgwt70_ElEl_MinusSM = new TH1F("h_ST_rgwt70_ElEl_MinusSM", "h_ST_rgwt70_ElEl_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt70_ElEl_MinusSM->Sumw2();
  TH1F *h_ST_rgwt71_ElEl_MinusSM = new TH1F("h_ST_rgwt71_ElEl_MinusSM", "h_ST_rgwt71_ElEl_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt71_ElEl_MinusSM->Sumw2();
  TH1F *h_ST_rgwt72_ElEl_MinusSM = new TH1F("h_ST_rgwt72_ElEl_MinusSM", "h_ST_rgwt72_ElEl_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt72_ElEl_MinusSM->Sumw2();
  TH1F *h_ST_rgwt73_ElEl_MinusSM = new TH1F("h_ST_rgwt73_ElEl_MinusSM", "h_ST_rgwt73_ElEl_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt73_ElEl_MinusSM->Sumw2();
  TH1F *h_ST_rgwt74_ElEl_MinusSM = new TH1F("h_ST_rgwt74_ElEl_MinusSM", "h_ST_rgwt74_ElEl_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt74_ElEl_MinusSM->Sumw2();
  TH1F *h_ST_rgwt75_ElEl_MinusSM = new TH1F("h_ST_rgwt75_ElEl_MinusSM", "h_ST_rgwt75_ElEl_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt75_ElEl_MinusSM->Sumw2();
  TH1F *h_ST_rgwt76_ElEl_MinusSM = new TH1F("h_ST_rgwt76_ElEl_MinusSM", "h_ST_rgwt76_ElEl_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt76_ElEl_MinusSM->Sumw2();
  TH1F *h_ST_rgwt77_ElEl_MinusSM = new TH1F("h_ST_rgwt77_ElEl_MinusSM", "h_ST_rgwt77_ElEl_MinusSM", 20.0, 0.0, 10000.0); h_ST_rgwt77_ElEl_MinusSM->Sumw2();
  TH1F *h_ST_bkg_ElEl_PlusSM = new TH1F("h_ST_bkg_ElEl_PlusSM", "h_ST_bkg_ElEl_PlusSM", 20.0, 0.0, 10000.0); h_ST_bkg_ElEl_PlusSM->Sumw2();

  int nEvents=tree->GetEntries();
  std::cout << "nEvents= " << nEvents << std::endl;

  for (int i=0; i<nEvents; ++i)
  {
    tree->GetEvent(i);
    h_ST_rgwt67_MuMu->Fill(ST_rwgt67_MuMu, weight_rwgt67_MuMu*LUMI*BR);
    h_ST_rgwt68_MuMu->Fill(ST_rwgt68_MuMu, weight_rwgt68_MuMu*LUMI*BR);
    h_ST_rgwt69_MuMu->Fill(ST_rwgt69_MuMu, weight_rwgt69_MuMu*LUMI*BR);
    h_ST_rgwt70_MuMu->Fill(ST_rwgt70_MuMu, weight_rwgt70_MuMu*LUMI*BR);
    h_ST_rgwt71_MuMu->Fill(ST_rwgt71_MuMu, weight_rwgt71_MuMu*LUMI*BR);
    h_ST_rgwt72_MuMu->Fill(ST_rwgt72_MuMu, weight_rwgt72_MuMu*LUMI*BR);
    h_ST_rgwt73_MuMu->Fill(ST_rwgt73_MuMu, weight_rwgt73_MuMu*LUMI*BR);
    h_ST_rgwt74_MuMu->Fill(ST_rwgt74_MuMu, weight_rwgt74_MuMu*LUMI*BR);
    h_ST_rgwt75_MuMu->Fill(ST_rwgt75_MuMu, weight_rwgt75_MuMu*LUMI*BR);
    h_ST_rgwt76_MuMu->Fill(ST_rwgt76_MuMu, weight_rwgt76_MuMu*LUMI*BR);
    h_ST_rgwt77_MuMu->Fill(ST_rwgt77_MuMu, weight_rwgt77_MuMu*LUMI*BR);
    h_ST_bkg_MuMu->Fill(ST_bkg_MuMu, weight_bkg_MuMu*LUMI);

    h_ST_rgwt67_ElMu->Fill(ST_rwgt67_ElMu, weight_rwgt67_ElMu*LUMI*BR);
    h_ST_rgwt68_ElMu->Fill(ST_rwgt68_ElMu, weight_rwgt68_ElMu*LUMI*BR);
    h_ST_rgwt69_ElMu->Fill(ST_rwgt69_ElMu, weight_rwgt69_ElMu*LUMI*BR);
    h_ST_rgwt70_ElMu->Fill(ST_rwgt70_ElMu, weight_rwgt70_ElMu*LUMI*BR);
    h_ST_rgwt71_ElMu->Fill(ST_rwgt71_ElMu, weight_rwgt71_ElMu*LUMI*BR);
    h_ST_rgwt72_ElMu->Fill(ST_rwgt72_ElMu, weight_rwgt72_ElMu*LUMI*BR);
    h_ST_rgwt73_ElMu->Fill(ST_rwgt73_ElMu, weight_rwgt73_ElMu*LUMI*BR);
    h_ST_rgwt74_ElMu->Fill(ST_rwgt74_ElMu, weight_rwgt74_ElMu*LUMI*BR);
    h_ST_rgwt75_ElMu->Fill(ST_rwgt75_ElMu, weight_rwgt75_ElMu*LUMI*BR);
    h_ST_rgwt76_ElMu->Fill(ST_rwgt76_ElMu, weight_rwgt76_ElMu*LUMI*BR);
    h_ST_rgwt77_ElMu->Fill(ST_rwgt77_ElMu, weight_rwgt77_ElMu*LUMI*BR);
    h_ST_bkg_ElMu->Fill(ST_bkg_ElMu, weight_bkg_ElMu*LUMI);

    h_ST_rgwt67_ElEl->Fill(ST_rwgt67_ElEl, weight_rwgt67_ElEl*LUMI*BR);
    h_ST_rgwt68_ElEl->Fill(ST_rwgt68_ElEl, weight_rwgt68_ElEl*LUMI*BR);
    h_ST_rgwt69_ElEl->Fill(ST_rwgt69_ElEl, weight_rwgt69_ElEl*LUMI*BR);
    h_ST_rgwt70_ElEl->Fill(ST_rwgt70_ElEl, weight_rwgt70_ElEl*LUMI*BR);
    h_ST_rgwt71_ElEl->Fill(ST_rwgt71_ElEl, weight_rwgt71_ElEl*LUMI*BR);
    h_ST_rgwt72_ElEl->Fill(ST_rwgt72_ElEl, weight_rwgt72_ElEl*LUMI*BR);
    h_ST_rgwt73_ElEl->Fill(ST_rwgt73_ElEl, weight_rwgt73_ElEl*LUMI*BR);
    h_ST_rgwt74_ElEl->Fill(ST_rwgt74_ElEl, weight_rwgt74_ElEl*LUMI*BR);
    h_ST_rgwt75_ElEl->Fill(ST_rwgt75_ElEl, weight_rwgt75_ElEl*LUMI*BR);
    h_ST_rgwt76_ElEl->Fill(ST_rwgt76_ElEl, weight_rwgt76_ElEl*LUMI*BR);
    h_ST_rgwt77_ElEl->Fill(ST_rwgt77_ElEl, weight_rwgt77_ElEl*LUMI*BR);
    h_ST_bkg_ElEl->Fill(ST_bkg_ElEl, weight_bkg_ElEl*LUMI); 

    for(int j=1; j<h_ST_rgwt67_MuMu->GetNbinsX()+1; j++) 
    {
      h_ST_rgwt67_MuMu_MinusSM->SetBinContent(j, (h_ST_rgwt67_MuMu->GetBinContent(j)-h_ST_rgwt72_MuMu->GetBinContent(j)));
      h_ST_rgwt68_MuMu_MinusSM->SetBinContent(j, (h_ST_rgwt68_MuMu->GetBinContent(j)-h_ST_rgwt72_MuMu->GetBinContent(j)));
      h_ST_rgwt69_MuMu_MinusSM->SetBinContent(j, (h_ST_rgwt69_MuMu->GetBinContent(j)-h_ST_rgwt72_MuMu->GetBinContent(j)));
      h_ST_rgwt70_MuMu_MinusSM->SetBinContent(j, (h_ST_rgwt70_MuMu->GetBinContent(j)-h_ST_rgwt72_MuMu->GetBinContent(j)));
      h_ST_rgwt71_MuMu_MinusSM->SetBinContent(j, (h_ST_rgwt71_MuMu->GetBinContent(j)-h_ST_rgwt72_MuMu->GetBinContent(j)));
      h_ST_rgwt72_MuMu_MinusSM->SetBinContent(j, (h_ST_rgwt72_MuMu->GetBinContent(j)-h_ST_rgwt72_MuMu->GetBinContent(j))+0.000001);
      h_ST_rgwt73_MuMu_MinusSM->SetBinContent(j, (h_ST_rgwt73_MuMu->GetBinContent(j)-h_ST_rgwt72_MuMu->GetBinContent(j)));
      h_ST_rgwt74_MuMu_MinusSM->SetBinContent(j, (h_ST_rgwt74_MuMu->GetBinContent(j)-h_ST_rgwt72_MuMu->GetBinContent(j)));
      h_ST_rgwt75_MuMu_MinusSM->SetBinContent(j, (h_ST_rgwt75_MuMu->GetBinContent(j)-h_ST_rgwt72_MuMu->GetBinContent(j)));
      h_ST_rgwt76_MuMu_MinusSM->SetBinContent(j, (h_ST_rgwt76_MuMu->GetBinContent(j)-h_ST_rgwt72_MuMu->GetBinContent(j)));
      h_ST_rgwt77_MuMu_MinusSM->SetBinContent(j, (h_ST_rgwt77_MuMu->GetBinContent(j)-h_ST_rgwt72_MuMu->GetBinContent(j)));

      h_ST_rgwt67_ElMu_MinusSM->SetBinContent(j, (h_ST_rgwt67_ElMu->GetBinContent(j)-h_ST_rgwt72_ElMu->GetBinContent(j)));
      h_ST_rgwt68_ElMu_MinusSM->SetBinContent(j, (h_ST_rgwt68_ElMu->GetBinContent(j)-h_ST_rgwt72_ElMu->GetBinContent(j)));
      h_ST_rgwt69_ElMu_MinusSM->SetBinContent(j, (h_ST_rgwt69_ElMu->GetBinContent(j)-h_ST_rgwt72_ElMu->GetBinContent(j)));
      h_ST_rgwt70_ElMu_MinusSM->SetBinContent(j, (h_ST_rgwt70_ElMu->GetBinContent(j)-h_ST_rgwt72_ElMu->GetBinContent(j)));
      h_ST_rgwt71_ElMu_MinusSM->SetBinContent(j, (h_ST_rgwt71_ElMu->GetBinContent(j)-h_ST_rgwt72_ElMu->GetBinContent(j)));
      h_ST_rgwt72_ElMu_MinusSM->SetBinContent(j, (h_ST_rgwt72_ElMu->GetBinContent(j)-h_ST_rgwt72_ElMu->GetBinContent(j))+0.000001);
      h_ST_rgwt73_ElMu_MinusSM->SetBinContent(j, (h_ST_rgwt73_ElMu->GetBinContent(j)-h_ST_rgwt72_ElMu->GetBinContent(j)));
      h_ST_rgwt74_ElMu_MinusSM->SetBinContent(j, (h_ST_rgwt74_ElMu->GetBinContent(j)-h_ST_rgwt72_ElMu->GetBinContent(j)));
      h_ST_rgwt75_ElMu_MinusSM->SetBinContent(j, (h_ST_rgwt75_ElMu->GetBinContent(j)-h_ST_rgwt72_ElMu->GetBinContent(j)));
      h_ST_rgwt76_ElMu_MinusSM->SetBinContent(j, (h_ST_rgwt76_ElMu->GetBinContent(j)-h_ST_rgwt72_ElMu->GetBinContent(j)));
      h_ST_rgwt77_ElMu_MinusSM->SetBinContent(j, (h_ST_rgwt77_ElMu->GetBinContent(j)-h_ST_rgwt72_ElMu->GetBinContent(j)));

      h_ST_rgwt67_ElEl_MinusSM->SetBinContent(j, (h_ST_rgwt67_ElEl->GetBinContent(j)-h_ST_rgwt72_ElEl->GetBinContent(j)));
      h_ST_rgwt68_ElEl_MinusSM->SetBinContent(j, (h_ST_rgwt68_ElEl->GetBinContent(j)-h_ST_rgwt72_ElEl->GetBinContent(j)));
      h_ST_rgwt69_ElEl_MinusSM->SetBinContent(j, (h_ST_rgwt69_ElEl->GetBinContent(j)-h_ST_rgwt72_ElEl->GetBinContent(j)));
      h_ST_rgwt70_ElEl_MinusSM->SetBinContent(j, (h_ST_rgwt70_ElEl->GetBinContent(j)-h_ST_rgwt72_ElEl->GetBinContent(j)));
      h_ST_rgwt71_ElEl_MinusSM->SetBinContent(j, (h_ST_rgwt71_ElEl->GetBinContent(j)-h_ST_rgwt72_ElEl->GetBinContent(j)));
      h_ST_rgwt72_ElEl_MinusSM->SetBinContent(j, (h_ST_rgwt72_ElEl->GetBinContent(j)-h_ST_rgwt72_ElEl->GetBinContent(j))+0.000001);
      h_ST_rgwt73_ElEl_MinusSM->SetBinContent(j, (h_ST_rgwt73_ElEl->GetBinContent(j)-h_ST_rgwt72_ElEl->GetBinContent(j)));
      h_ST_rgwt74_ElEl_MinusSM->SetBinContent(j, (h_ST_rgwt74_ElEl->GetBinContent(j)-h_ST_rgwt72_ElEl->GetBinContent(j)));
      h_ST_rgwt75_ElEl_MinusSM->SetBinContent(j, (h_ST_rgwt75_ElEl->GetBinContent(j)-h_ST_rgwt72_ElEl->GetBinContent(j)));
      h_ST_rgwt76_ElEl_MinusSM->SetBinContent(j, (h_ST_rgwt76_ElEl->GetBinContent(j)-h_ST_rgwt72_ElEl->GetBinContent(j)));
      h_ST_rgwt77_ElEl_MinusSM->SetBinContent(j, (h_ST_rgwt77_ElEl->GetBinContent(j)-h_ST_rgwt72_ElEl->GetBinContent(j)));

      h_ST_bkg_MuMu_PlusSM->SetBinContent(j, (h_ST_bkg_MuMu->GetBinContent(j)+h_ST_rgwt72_MuMu->GetBinContent(j)));
      h_ST_bkg_ElMu_PlusSM->SetBinContent(j, (h_ST_bkg_ElMu->GetBinContent(j)+h_ST_rgwt72_ElMu->GetBinContent(j)));
      h_ST_bkg_ElEl_PlusSM->SetBinContent(j, (h_ST_bkg_ElEl->GetBinContent(j)+h_ST_rgwt72_ElEl->GetBinContent(j))); 
    }
  }

  std::string histfilename=(outfile+".root").c_str();
  TFile *tFile=new TFile(histfilename.c_str(), "RECREATE");
  h_ST_rgwt67_MuMu->Write();
  h_ST_rgwt68_MuMu->Write();
  h_ST_rgwt69_MuMu->Write();
  h_ST_rgwt70_MuMu->Write();
  h_ST_rgwt71_MuMu->Write();
  h_ST_rgwt72_MuMu->Write();
  h_ST_rgwt73_MuMu->Write();
  h_ST_rgwt74_MuMu->Write();
  h_ST_rgwt75_MuMu->Write();
  h_ST_rgwt76_MuMu->Write();
  h_ST_rgwt77_MuMu->Write();
  h_ST_rgwt67_ElMu->Write();
  h_ST_rgwt68_ElMu->Write();
  h_ST_rgwt69_ElMu->Write();
  h_ST_rgwt70_ElMu->Write();
  h_ST_rgwt71_ElMu->Write();
  h_ST_rgwt72_ElMu->Write();
  h_ST_rgwt73_ElMu->Write();
  h_ST_rgwt74_ElMu->Write();
  h_ST_rgwt75_ElMu->Write();
  h_ST_rgwt76_ElMu->Write();
  h_ST_rgwt77_ElMu->Write();
  h_ST_rgwt67_ElEl->Write();
  h_ST_rgwt68_ElEl->Write();
  h_ST_rgwt69_ElEl->Write();
  h_ST_rgwt70_ElEl->Write();
  h_ST_rgwt71_ElEl->Write();
  h_ST_rgwt72_ElEl->Write();
  h_ST_rgwt73_ElEl->Write();
  h_ST_rgwt74_ElEl->Write();
  h_ST_rgwt75_ElEl->Write();
  h_ST_rgwt76_ElEl->Write();
  h_ST_rgwt77_ElEl->Write();
  h_ST_rgwt67_MuMu_MinusSM->Write();
  h_ST_rgwt68_MuMu_MinusSM->Write();
  h_ST_rgwt69_MuMu_MinusSM->Write();
  h_ST_rgwt70_MuMu_MinusSM->Write();
  h_ST_rgwt71_MuMu_MinusSM->Write();
  h_ST_rgwt72_MuMu_MinusSM->Write();
  h_ST_rgwt73_MuMu_MinusSM->Write();
  h_ST_rgwt74_MuMu_MinusSM->Write();
  h_ST_rgwt75_MuMu_MinusSM->Write();
  h_ST_rgwt76_MuMu_MinusSM->Write();
  h_ST_rgwt77_MuMu_MinusSM->Write();
  h_ST_rgwt67_ElMu_MinusSM->Write();
  h_ST_rgwt68_ElMu_MinusSM->Write();
  h_ST_rgwt69_ElMu_MinusSM->Write();
  h_ST_rgwt70_ElMu_MinusSM->Write();
  h_ST_rgwt71_ElMu_MinusSM->Write();
  h_ST_rgwt72_ElMu_MinusSM->Write();
  h_ST_rgwt73_ElMu_MinusSM->Write();
  h_ST_rgwt74_ElMu_MinusSM->Write();
  h_ST_rgwt75_ElMu_MinusSM->Write();
  h_ST_rgwt76_ElMu_MinusSM->Write();
  h_ST_rgwt77_ElMu_MinusSM->Write();
  h_ST_rgwt67_ElEl_MinusSM->Write();
  h_ST_rgwt68_ElEl_MinusSM->Write();
  h_ST_rgwt69_ElEl_MinusSM->Write();
  h_ST_rgwt70_ElEl_MinusSM->Write();
  h_ST_rgwt71_ElEl_MinusSM->Write();
  h_ST_rgwt72_ElEl_MinusSM->Write();
  h_ST_rgwt73_ElEl_MinusSM->Write();
  h_ST_rgwt74_ElEl_MinusSM->Write();
  h_ST_rgwt75_ElEl_MinusSM->Write();
  h_ST_rgwt76_ElEl_MinusSM->Write();
  h_ST_rgwt77_ElEl_MinusSM->Write();
  h_ST_bkg_MuMu->Write();
  h_ST_bkg_ElMu->Write();
  h_ST_bkg_ElEl->Write();
  h_ST_bkg_MuMu_PlusSM->Write();
  h_ST_bkg_ElMu_PlusSM->Write();
  h_ST_bkg_ElEl_PlusSM->Write();
  tFile->Close(); 
  std::cout<<"Wrote output file "<<histfilename<<std::endl;
  return 0;
}
